<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons [
<!ELEMENT persons (person)*>
<!ELEMENT person (id , name , type , username , password)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
]>
<persons>
    <person>
        <id>1</id>
        <name>Saef Ullah Miah</name>
        <type>teacher</type>
        <username>1111</username>
        <password>1234</password>
    </person>
    <person>
        <id>2</id>
        <name>Talha Bin Sarwar</name>
        <type>teacher</type>
        <username>2222</username>
        <password>1234</password>
    </person>
    <person>
        <id>3</id>
        <name>Shahriar Alam</name>
        <type>student</type>
        <username>3333</username>
        <password>1234</password>
    </person>
    <person>
        <id>4</id>
        <name>Tanmoy Roy</name>
        <type>student</type>
        <username>4444</username>
        <password>1234</password>
    </person>
    <person>
        <id>5</id>
        <name>Hasib Rafi</name>
        <type>student</type>
        <username>5555</username>
        <password>1234</password>
    </person>
</persons>
